development:
  secret_key_base: key
  publishable_key: pk_test_LgTd3nC3OBvUPAvzKoY6bkBa00AbSsBZHl
  secret_key: sk_test_yDzMuguOj0N0qhyYALJvR9Go00xOWDMCST

test:
  secret_key_base:

production:
  secret_key_base: key
  publishable_key: pk_test_LgTd3nC3OBvUPAvzKoY6bkBa00AbSsBZHl
  secret_key: sk_test_yDzMuguOj0N0qhyYALJvR9Go00xOWDMCST
